import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { SessionProvider } from 'next-auth/react';
import { ThemeProvider } from '@/core/providers/theme-provider';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { MuiThemeBridge } from '@/core/providers/mui-theme-provider';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  weight: ['400', '700'],
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider>
            <MuiThemeBridge>
              <SessionProvider>{children}</SessionProvider>
            </MuiThemeBridge>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
