import type { Metadata } from 'next';
import { AR_One_Sans, Inter } from 'next/font/google';

import Providers from '@/core/providers';

import './globals.css';

const arOneSans = AR_One_Sans({
  variable: '--font-ar-one-sans',
  weight: ['400', '700'],
  subsets: ['latin'],
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${inter.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
